cmake_minimum_required(VERSION 3.20)
project(UniversityLabs C)

set(CMAKE_C_STANDARD 99)


add_executable(Task4 12_pack/4.c)
add_executable(Task5 12_pack/5.c)
add_executable(Task6 12_pack/6.c)
add_executable(Task7 12_pack/7.c)
add_executable(Task5_2 13_pack/5.c)
add_executable(Task1_2 13_pack/1.c)
add_executable(Task2_2 13_pack/2.c)
add_executable(Task3_2 13_pack/3.c)
